name: RankPrefixPlus
version: ${project.version}
author: THeBusyBiscuit
website: http://TheBusyBiscuit.github.io

main: io.github.thebusybiscuit.rankprefixplus.RankPrefixPlus
api-version: 1.13

permissions:
  RankPrefixPlus.chatcolors:
    default: op
    description: Allows you to use Chat Colors
  RankPrefixPlus.reload:
    default: op
    description: Allows you to reload the Config

commands:
  rpreload:
    usage: /rpreload
    description: Reloads the RankPrefix+ Config